/* Auto-generated from config.json — do not edit this file directly */
:root {
  --accent:      {{theme.accent}};
  --accent-dark: {{theme.accent_dark}};
  --ember:       {{theme.ember}};
  --gold:        {{theme.gold}};
  --chili-oil:   linear-gradient(125deg, {{theme.chili_from}} 0%, {{theme.accent}} 42%, {{theme.ember}} 100%);
  --cream:       {{theme.cream}};
  --cream-deep:  {{theme.cream_deep}};
  --ink:         {{theme.ink}};
  --font-head:   '{{theme.font_head}}', system-ui, sans-serif;
  --font-ui:     '{{theme.font_head}}', system-ui, sans-serif;
  --font-body:   '{{theme.font_body}}', system-ui, sans-serif;
}
